### ISSUE TITLE
Cannot save best model

### ISSUE THREAD

**Issue by gnorZgnoD** [JusperLee/S4M#2]
Hi author,
  When i finished the training process, i met the following issue. I used the python==3.9, torch==2.0.0+cu118, torchaudio==2.0.1+cu118, and pytorch-lightning==2.0.4. How can i sovle it?
![image](https://github.com/JusperLee/S4M/assets/105347776/faf9df7e-0a70-4049-ae99-1083ea96f3b8)

**Comment by JusperLee** [comment]
You need use the basemodel 
https://github.com/JusperLee/TDANet/blob/main/look2hear/models/base_model.py

**Comment by gnorZgnoD** [comment]
I solved the problem followed your suggestion, tks!
